version: "3.9"

services:

  db:
    build:
      context: database
    container_name: database
    image: dbz-database
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      - "MYSQL_ROOT_PASSWORD=rootroot"
    ports:
      - "3306:3306"
